networks:
  spark_net:
    name: spark_net
    driver: bridge

services:
  spark:
    build:
      context: .
      dockerfile: Dockerfile
    image: spark
    # ports:
      # - ""
    networks:
      - spark_net
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 5s
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '1.0'
          memory: 256M
