[tls]
enabled = false
cert_file = "/etc/letsencrypt/live/sub.domain.tld/fullchain.pem"
key_file = "/etc/letsencrypt/live/sub.domain.tld/privkey.pem"

[server]
addr = ":8081"
prefork = true

[xray]
addr = "127.0.0.1:8082"

[auth]
secret = "secret!"
