[tls]
enabled = true
cert_file = "/etc/letsencrypt/live/sub.domain.tld/fullchain.pem"
key_file = "/etc/letsencrypt/live/sub.domain.tld/privkey.pem"

[server]
addr = ":10100"
prefork = true

[xray]
addr = "127.0.0.1:8080"

[auth]
secret = "secret!"
